/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author feisal
 */
public class MenuUtama extends javax.swing.JFrame {
    public MenuUtama() {
        initComponents();
        jMenuBar1.remove(jLogout); 
        try { jMenuBar1.remove(filler1); } catch (Exception e) {}
        jMenuBar1.add(javax.swing.Box.createHorizontalGlue());
        jMenuBar1.add(jLogout); 
        jMenuBar1.revalidate();
        jMenuBar1.repaint();
        this.setSize(800, 520); 
        this.setLocationRelativeTo(null); 
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setForeground(new java.awt.Color(30, 60, 114, 50)); 
    }
    public void setHakAkses(String level) {
        if (level.equals("admin")) {
            menuMaster.setEnabled(true);
            menuTransaksi.setEnabled(true); 
            menuItemAddUser.setEnabled(true);
            menuItemChangePass.setEnabled(true); 
            
        } else if (level.equals("operator")) {
            menuMaster.setEnabled(false);
            menuTransaksi.setEnabled(true);
            menuItemAddUser.setEnabled(false);
            menuItemChangePass.setEnabled(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        jMenuBar1 = new javax.swing.JMenuBar();
        menuMaster = new javax.swing.JMenu();
        miDosen = new javax.swing.JMenuItem();
        miMahasiswa = new javax.swing.JMenuItem();
        miMataKuliah = new javax.swing.JMenuItem();
        menuTransaksi = new javax.swing.JMenu();
        miIsiKRS = new javax.swing.JMenuItem();
        miInputNilai = new javax.swing.JMenuItem();
        miEditNilai = new javax.swing.JMenuItem();
        menuSettings = new javax.swing.JMenu();
        menuItemAddUser = new javax.swing.JMenuItem();
        menuItemChangePass = new javax.swing.JMenuItem();
        jLogout = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 520));

        jPanel1.setBackground(new java.awt.Color(240, 244, 250));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 90)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(30, 60, 114));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("<html>\n<center><span style=\"font-size: 72px; font-weight: bold;\">UTB</span>\n<br>\n<span style=\"font-size: 12px;\">Sistem Informasi Akademik</span></center>\n</html>");
        jPanel1.add(jLabel1, new java.awt.GridBagConstraints());

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);
        getContentPane().add(filler1, java.awt.BorderLayout.PAGE_START);

        menuMaster.setText("File Master");

        miDosen.setText("Dosen");
        miDosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miDosenActionPerformed(evt);
            }
        });
        menuMaster.add(miDosen);

        miMahasiswa.setText("Mahasiswa");
        miMahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miMahasiswaActionPerformed(evt);
            }
        });
        menuMaster.add(miMahasiswa);

        miMataKuliah.setText("Mata Kuliah");
        miMataKuliah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miMataKuliahActionPerformed(evt);
            }
        });
        menuMaster.add(miMataKuliah);

        jMenuBar1.add(menuMaster);

        menuTransaksi.setText("Transaction");

        miIsiKRS.setText("Isi KRS");
        miIsiKRS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miIsiKRSActionPerformed(evt);
            }
        });
        menuTransaksi.add(miIsiKRS);

        miInputNilai.setText("Input Nilai");
        miInputNilai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miInputNilaiActionPerformed(evt);
            }
        });
        menuTransaksi.add(miInputNilai);

        miEditNilai.setText("Edit / Hapus Nilai");
        miEditNilai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miEditNilaiActionPerformed(evt);
            }
        });
        menuTransaksi.add(miEditNilai);

        jMenuBar1.add(menuTransaksi);

        menuSettings.setText("Settings");

        menuItemAddUser.setText("Add User");
        menuItemAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAddUserActionPerformed(evt);
            }
        });
        menuSettings.add(menuItemAddUser);

        menuItemChangePass.setText("Change Password");
        menuItemChangePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemChangePassActionPerformed(evt);
            }
        });
        menuSettings.add(menuItemChangePass);

        jMenuBar1.add(menuSettings);

        jLogout.setText("Log-out");
        jLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLogoutMouseClicked(evt);
            }
        });
        jMenuBar1.add(jLogout);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miDosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miDosenActionPerformed
        FormDosen dsn = new FormDosen();
dsn.setVisible(true);
    }//GEN-LAST:event_miDosenActionPerformed

    private void menuItemAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAddUserActionPerformed
        FormUser fu = new FormUser();
fu.setVisible(true);
    }//GEN-LAST:event_menuItemAddUserActionPerformed

    private void miIsiKRSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miIsiKRSActionPerformed
        FormKrs krs = new FormKrs();
krs.setVisible(true);
    }//GEN-LAST:event_miIsiKRSActionPerformed

    private void menuItemChangePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemChangePassActionPerformed
        FormUbahPassword pass = new FormUbahPassword();
pass.setVisible(true);
    }//GEN-LAST:event_menuItemChangePassActionPerformed

    private void miMahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miMahasiswaActionPerformed
        new FormMahasiswa().setVisible(true);
    }//GEN-LAST:event_miMahasiswaActionPerformed

    private void miMataKuliahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miMataKuliahActionPerformed
        new FormMatakuliah().setVisible(true);
    }//GEN-LAST:event_miMataKuliahActionPerformed

    private void miInputNilaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miInputNilaiActionPerformed
        new  FormSoal1().setVisible(true);
    }//GEN-LAST:event_miInputNilaiActionPerformed

    private void jLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLogoutMouseClicked
        int konfirmasi = javax.swing.JOptionPane.showConfirmDialog(this, 
            "Yakin ingin Log-out?", "Konfirmasi", 
            javax.swing.JOptionPane.YES_NO_OPTION);
    
    if (konfirmasi == javax.swing.JOptionPane.YES_OPTION) {
        new FormLogin().setVisible(true);
        this.dispose(); 
    }
    }//GEN-LAST:event_jLogoutMouseClicked

    private void miEditNilaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miEditNilaiActionPerformed
        new FormNilaiEdit().setVisible(true);
    }//GEN-LAST:event_miEditNilaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jLogout;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem menuItemAddUser;
    private javax.swing.JMenuItem menuItemChangePass;
    private javax.swing.JMenu menuMaster;
    private javax.swing.JMenu menuSettings;
    private javax.swing.JMenu menuTransaksi;
    private javax.swing.JMenuItem miDosen;
    private javax.swing.JMenuItem miEditNilai;
    private javax.swing.JMenuItem miInputNilai;
    private javax.swing.JMenuItem miIsiKRS;
    private javax.swing.JMenuItem miMahasiswa;
    private javax.swing.JMenuItem miMataKuliah;
    // End of variables declaration//GEN-END:variables
}
